#pragma once
#include <simulation\game_interface\simulation_game_engine_globals.h>

enum e_simulation_vip_engine_globals_update_flag
{
	_simulation_vip_engine_globals_update_player1 = k_simulation_game_engine_globals_flag_count,
	_simulation_vip_engine_globals_update_player2,
	_simulation_vip_engine_globals_update_player3,
	_simulation_vip_engine_globals_update_player4,
	_simulation_vip_engine_globals_update_player5,
	_simulation_vip_engine_globals_update_player6,
	_simulation_vip_engine_globals_update_player7,
	_simulation_vip_engine_globals_update_player8,
	_simulation_vip_engine_globals_update_unused1,
	_simulation_vip_engine_globals_update_destination_zone1,
	_simulation_vip_engine_globals_update_destination_zone2,
	_simulation_vip_engine_globals_update_destination_zone3,
	_simulation_vip_engine_globals_update_destination_zone4,
	_simulation_vip_engine_globals_update_destination_zone5,
	_simulation_vip_engine_globals_update_destination_zone6,
	_simulation_vip_engine_globals_update_destination_zone7,
	_simulation_vip_engine_globals_update_destination_zone8,
	_simulation_vip_engine_globals_update_destination_zone9,
	_simulation_vip_engine_globals_update_destination_zone10,
	_simulation_vip_engine_globals_update_destination_zone11,
	_simulation_vip_engine_globals_update_destination_zone12,
	_simulation_vip_engine_globals_update_unused2,
	_simulation_vip_engine_globals_update_unknown29, // updates __unknown20 in s_vip_globals

	k_simulation_vip_engine_globals_flag_count
};