#pragma once

enum e_desired_multiplayer_mode;
class c_game_variant;
class c_map_variant;

bool __fastcall user_interface_squad_set_game_variant(c_game_variant* game_variant);
bool __fastcall user_interface_squad_set_multiplayer_map(c_map_variant* map_variant);
void __fastcall user_interface_set_desired_multiplayer_mode(e_desired_multiplayer_mode multiplayer_mode);