#pragma once
#include "..\cseries\cseries.h"
#include "..\game\players.h"
#include "data.h"

struct s_player_datum : s_datum // belongs in game\players\players.h
{
	short unknown;
	dword_flags flags;
	s_player_identifier player_identifier;
	ulong left_game_time;
	s_machine_identifier machine_identifier; // secure_address / xnaddr
	short machine_index;
	short machine_input_user_index;
	long machine_controller_index;
	short location;
	datum_index unit_index;
	datum_index dead_unit_index;
	datum_index previous_unit_index;
	// INCOMPLETE
};
// TODO size

struct s_player_mapping
{
	short active_input_user_count;
	short active_input_controller_count;
	ulong input_user_player_mapping[4];
	datum_index input_user_unit_mapping[4];
	ulong input_controller_player_mapping[4];
	ulong player_input_controller_mapping[16];
	ulong player_input_user_mapping[16];
	ulong active_output_user_count;
	ulong output_user_player_mapping[4];
	datum_index output_user_unit_mapping[4];
	byte player_output_user_mapping[16];
};

struct s_thread_local_storage
{
	byte* __unknown0;
	byte* __unknown4;
	byte* g_players_data; // s_player_datum array?
	byte* __unknownC;
	struct s_game_engine_globals* g_game_engine_globals;
	byte* __unknown14;
	byte* __unknown18;
	byte* __unknown1C;
	struct global_preferences* g_global_preferences;
	struct game_globals* g_game_globals;
	byte* __unknown28;
	struct s_scripted_camera_globals* g_scripted_camera_globals;
	struct players_global_data* g_players_globals;
	byte* __unknown34;
	byte* __unknown38;
	byte* __unknown3C;
	byte* __unknown40;
	byte* __unknown44;
	byte* __unknown48;
	struct s_player_control_globals* g_player_control_globals;
	byte* __unknown50;
	byte* g_campaign_metagame_globals;
	byte* g_breakable_surface_globals;
	byte* g_timing_samples_global;
	byte* __unknown60;
	struct game_time_globals_definition* g_game_time_globals;
	byte* __unknown68;
	byte* __unknown6C;
	struct s_data_array* g_object_looping_sounds_data;
	byte* __unknown74;
	byte* __unknown78;
	byte* __unknown7C;
	byte* __unknown80;
	s_player_mapping* g_player_mapping_globals;
	byte* __unknown88;
	byte* __unknown8C;
	byte* __unknown90;
	byte* __unknown94;
	byte* __unknown98;
	byte* __unknown9C;
	byte* __unknownA0;
	byte* __unknownA4;
	byte* __unknownA8;
	byte* __unknownAC;
	byte* __unknownB0;
	struct s_game_sound_globals* g_game_sound_globals;
	byte* __unknownB8;
	byte* __unknownBC;
	byte* g_director_globals;
	byte* __unknownC4;
	byte* __unknownC8;
	byte* __unknownCC;
	byte* __unknownD0;
	byte* __unknownD4;
	byte* __unknownD8;
	byte* __unknownDC;
	byte* __unknownE0;
	byte* g_effect_counts;
	byte* __unknownE8;
	byte* __unknownEC;
	byte* __unknownF0;
	byte* __unknownF4;
	byte* __unknownF8;
	byte* __unknownFC;
	byte* __unknown100;
	byte* __unknown104;
	struct s_data_array* g_breakable_surface_set_broken_events_data;
	byte* __unknown10C;
	byte* __unknown110;
	byte* __unknown114;
	byte* __unknown118;
	byte* __unknown11C;
	byte* __unknown120;
	byte* __unknown124;
	byte* __unknown128;
	byte* __unknown12C;
	struct s_data_array* __unknown130;
	byte* __unknown134;
	byte* __unknown138;
	byte* __unknown13C;
	byte* __unknown140;
	byte* __unknown144;
	byte* __unknown148;
	byte* g_local_game_engine_globals;
	byte* __unknown150;
	byte* __unknown154;
	byte* __unknown158;
	byte* __unknown15C;
	byte* __unknown160;
	byte* __unknown164;
	struct s_data_array* g_effect_geometry_sample_data;
	byte* __unknown16C;
	byte* __unknown170;
	byte* __unknown174;
	byte* __unknown178;
	byte* __unknown17C;
	byte* __unknown180;
	byte* __unknown184;
	byte* __unknown188;
	byte* g_game_sound_scripted_impulses_globals;
	byte* __unknown190;
	byte* __unknown194;
	byte* __unknown198;
	byte* __unknown19C;
	byte* __unknown1A0;
	byte* __unknown1A4;
	byte* __unknown1A8;
	byte* __unknown1AC;
	byte* __unknown1B0;
	byte* __unknown1B4;
	byte* __unknown1B8;
	byte* __unknown1BC;
	byte* __unknown1C0;
	byte* __unknown1C4;
	byte* __unknown1C8;
	byte* __unknown1CC;
	byte* __unknown1D0;
	byte* __unknown1D4;
	byte* __unknown1D8;
	byte* __unknown1DC;
	byte* __unknown1E0;
	byte* __unknown1E4;
	byte* __unknown1E8;
	byte* __unknown1EC;
	byte* __unknown1F0;
	byte* __unknown1F4;
	byte* __unknown1F8;
	byte* __unknown1FC;
	byte* __unknown200;
	byte* __unknown204;
	byte* __unknown208;
	byte* __unknown20C;
	byte* __unknown210;
	byte* __unknown214;
	byte* __unknown218;
	byte* g_effect_messaging_queue;
	byte* g_effect_lightprobes;
	byte* g_player_control_globals_deterministic;
	byte* __unknown228;
	byte* __unknown22C;
	byte* __unknown230;
	byte* __unknown234;
	byte* __unknown238;
	byte* __unknown23C;
	byte* __unknown240;
	byte* __unknown244;
	byte* __unknown248;
	byte* __unknown24C;
	byte* __unknown250;
	byte* __unknown254;
	byte* __unknown258;
	byte* __unknown25C;
	byte* __unknown260;
	byte* __unknown264;
	byte* __unknown268;
	byte* __unknown26C;
	byte* __unknown270;
	byte* __unknown274;
	byte* __unknown278;
	byte* __unknown27C;
	byte* __unknown280;
	byte* __unknown284;
	byte* __unknown288;
	byte* __unknown28C;
	byte* __unknown290;
	byte* __unknown294;
	byte* __unknown298;
	byte* __unknown29C;
	byte* g_random_math_globals;
	byte* __unknown2A4;
	byte* __unknown2A8;
	byte* __unknown2AC;
	byte* __unknown2B0;
	byte* __unknown2B4;
	byte* __unknown2B8;
	byte* __unknown2BC;
	byte* __unknown2C0;
	byte* __unknown2C4;
	byte* __unknown2C8;
	byte* __unknown2CC;
	byte* __unknown2D0;
	byte* __unknown2D4;
	byte* __unknown2D8;
	byte* __unknown2DC;
	byte* __unknown2E0;
	byte* __unknown2E4;
	byte* __unknown2E8;
	byte* __unknown2EC;
	byte* __unknown2F0;
	byte* __unknown2F4;
	byte* __unknown2F8;
	byte* __unknown2FC;
	byte* __unknown300;
	byte* __unknown304;
	byte* __unknown308;
	byte* __unknown30C;
	byte* __unknown310;
	byte* __unknown314;
	byte* __unknown318;
	byte* __unknown31C;
	byte* __unknown320;
	byte* __unknown324;
	byte* __unknown328;
	byte* __unknown32C;
	byte* __unknown330;
	byte* __unknown334;
	byte* __unknown338;
	byte* __unknown33C;
	byte* __unknown340;
	byte* __unknown344;
	byte* __unknown348;
	byte* __unknown34C;
};
static_assert(sizeof(s_thread_local_storage) == 0x350);

void* tls_get(const dword offset = 0);