#pragma once
#include "../game/players.h"
#include "data.h"
#include <cstdint>
#include <windows.h>

struct s_player_datum : s_datum // belongs in game\players\players.h
{
	short unknown;
	uint32_t flags;
	s_player_identifier player_identifier;
	uint32_t left_game_time;
	s_machine_identifier machine_identifier; // secure_address / xnaddr
	short machine_index;
	short machine_input_user_index;
	long machine_controller_index;
	short location;
	datum_index unit_index;
	datum_index dead_unit_index;
	datum_index previous_unit_index;
	// INCOMPLETE
};
// TODO size

struct s_player_mapping
{
	int16_t active_input_user_count;
	int16_t active_input_controller_count;
	uint32_t input_user_player_mapping[4];
	datum_index input_user_unit_mapping[4];
	uint32_t input_controller_player_mapping[4];
	uint32_t player_input_controller_mapping[16];
	uint32_t player_input_user_mapping[16];
	uint32_t active_output_user_count;
	uint32_t output_user_player_mapping[4];
	datum_index output_user_unit_mapping[4];
	byte player_output_user_mapping[16];
};

struct s_thread_local_storage
{
	char* __unknown0;
	char* __unknown4;
	char* g_players_data; // s_player_datum array?
	char* __unknownC;
	struct s_game_engine_globals* g_game_engine_globals;
	char* __unknown14;
	char* __unknown18;
	char* __unknown1C;
	struct global_preferences* g_global_preferences;
	struct game_globals* g_game_globals;
	char* __unknown28;
	struct s_scripted_camera_globals* g_scripted_camera_globals;
	struct players_global_data* g_players_globals;
	char* __unknown34;
	char* __unknown38;
	char* __unknown3C;
	char* __unknown40;
	char* __unknown44;
	char* __unknown48;
	struct s_player_control_globals* g_player_control_globals;
	char* __unknown50;
	char* g_campaign_metagame_globals;
	char* g_breakable_surface_globals;
	char* g_timing_samples_global;
	char* __unknown60;
	struct game_time_globals_definition* g_game_time_globals;
	char* __unknown68;
	char* __unknown6C;
	struct s_data_array* g_object_looping_sounds_data;
	char* __unknown74;
	char* __unknown78;
	char* __unknown7C;
	char* __unknown80;
	s_player_mapping* g_player_mapping_globals;
	char* __unknown88;
	char* __unknown8C;
	char* __unknown90;
	char* __unknown94;
	char* __unknown98;
	char* __unknown9C;
	char* __unknownA0;
	char* __unknownA4;
	char* __unknownA8;
	char* __unknownAC;
	char* __unknownB0;
	struct s_game_sound_globals* g_game_sound_globals;
	char* __unknownB8;
	char* __unknownBC;
	char* g_director_globals;
	char* __unknownC4;
	char* __unknownC8;
	char* __unknownCC;
	char* __unknownD0;
	char* __unknownD4;
	char* __unknownD8;
	char* __unknownDC;
	char* __unknownE0;
	char* g_effect_counts;
	char* __unknownE8;
	char* __unknownEC;
	char* __unknownF0;
	char* __unknownF4;
	char* __unknownF8;
	char* __unknownFC;
	char* __unknown100;
	char* __unknown104;
	struct s_data_array* g_breakable_surface_set_broken_events_data;
	char* __unknown10C;
	char* __unknown110;
	char* __unknown114;
	char* __unknown118;
	char* __unknown11C;
	char* __unknown120;
	char* __unknown124;
	char* __unknown128;
	char* __unknown12C;
	struct s_data_array* __unknown130;
	char* __unknown134;
	char* __unknown138;
	char* __unknown13C;
	char* __unknown140;
	char* __unknown144;
	char* __unknown148;
	char* g_local_game_engine_globals;
	char* __unknown150;
	char* __unknown154;
	char* __unknown158;
	char* __unknown15C;
	char* __unknown160;
	char* __unknown164;
	struct s_data_array* g_effect_geometry_sample_data;
	char* __unknown16C;
	char* __unknown170;
	char* __unknown174;
	char* __unknown178;
	char* __unknown17C;
	char* __unknown180;
	char* __unknown184;
	char* __unknown188;
	char* g_game_sound_scripted_impulses_globals;
	char* __unknown190;
	char* __unknown194;
	char* __unknown198;
	char* __unknown19C;
	char* __unknown1A0;
	char* __unknown1A4;
	char* __unknown1A8;
	char* __unknown1AC;
	char* __unknown1B0;
	char* __unknown1B4;
	char* __unknown1B8;
	char* __unknown1BC;
	char* __unknown1C0;
	char* __unknown1C4;
	char* __unknown1C8;
	char* __unknown1CC;
	char* __unknown1D0;
	char* __unknown1D4;
	char* __unknown1D8;
	char* __unknown1DC;
	char* __unknown1E0;
	char* __unknown1E4;
	char* __unknown1E8;
	char* __unknown1EC;
	char* __unknown1F0;
	char* __unknown1F4;
	char* __unknown1F8;
	char* __unknown1FC;
	char* __unknown200;
	char* __unknown204;
	char* __unknown208;
	char* __unknown20C;
	char* __unknown210;
	char* __unknown214;
	char* __unknown218;
	char* g_effect_messaging_queue;
	char* g_effect_lightprobes;
	char* g_player_control_globals_deterministic;
	char* __unknown228;
	char* __unknown22C;
	char* __unknown230;
	char* __unknown234;
	char* __unknown238;
	char* __unknown23C;
	char* __unknown240;
	char* __unknown244;
	char* __unknown248;
	char* __unknown24C;
	char* __unknown250;
	char* __unknown254;
	char* __unknown258;
	char* __unknown25C;
	char* __unknown260;
	char* __unknown264;
	char* __unknown268;
	char* __unknown26C;
	char* __unknown270;
	char* __unknown274;
	char* __unknown278;
	char* __unknown27C;
	char* __unknown280;
	char* __unknown284;
	char* __unknown288;
	char* __unknown28C;
	char* __unknown290;
	char* __unknown294;
	char* __unknown298;
	char* __unknown29C;
	char* g_random_math_globals;
	char* __unknown2A4;
	char* __unknown2A8;
	char* __unknown2AC;
	char* __unknown2B0;
	char* __unknown2B4;
	char* __unknown2B8;
	char* __unknown2BC;
	char* __unknown2C0;
	char* __unknown2C4;
	char* __unknown2C8;
	char* __unknown2CC;
	char* __unknown2D0;
	char* __unknown2D4;
	char* __unknown2D8;
	char* __unknown2DC;
	char* __unknown2E0;
	char* __unknown2E4;
	char* __unknown2E8;
	char* __unknown2EC;
	char* __unknown2F0;
	char* __unknown2F4;
	char* __unknown2F8;
	char* __unknown2FC;
	char* __unknown300;
	char* __unknown304;
	char* __unknown308;
	char* __unknown30C;
	char* __unknown310;
	char* __unknown314;
	char* __unknown318;
	char* __unknown31C;
	char* __unknown320;
	char* __unknown324;
	char* __unknown328;
	char* __unknown32C;
	char* __unknown330;
	char* __unknown334;
	char* __unknown338;
	char* __unknown33C;
	char* __unknown340;
	char* __unknown344;
	char* __unknown348;
	char* __unknown34C;
};
static_assert(sizeof(s_thread_local_storage) == 0x350);

void* tls_get(const unsigned long offset = 0);