#pragma once

struct s_game_globals* scenario_get_game_globals();
struct s_game_globals* scenario_try_and_get_game_globals();
struct s_multiplayer_universal_globals_definition* scenario_multiplayer_globals_try_and_get_universal_data();
struct s_multiplayer_runtime_globals_definition* scenario_multiplayer_globals_try_and_get_runtime_data();
long multiplayer_globals_get_equipment_count();